[package]
name = "github-issues"
version = "0.1.0"
authors = ["Guillaume Desmottes <guillaume.desmottes@collabora.co.uk>"]

[dependencies]
github-rs = "0.6"
serde = "1.0"
serde_json = "1.0"
serde_derive = "1.0"
url = "1.7.0"
structopt = "0.2"
csv = "1.0.0-beta.5"
